using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;

//--------------------------------------------------------------------------------
//-- Generated By: Slava
//-- Date Generated: 05/13/2017
//--------------------------------------------------------------------------------
namespace RifleRange.DAL
{

    public class rrForum
    {
        [SqlField]
        public int ForumId { get; set; }
        [SqlField]
        public string Title { get; set; }
        [SqlField]
        public string Description { get; set; }
        [SqlField]
        public int NumTopics { get; set; }
        [SqlField]
        public int NumMessages { get; set; }
        [SqlField]
        public bool NotLoggedInRead { get; set; }
        [SqlField]
        public bool NotLoggedInReply { get; set; }
        [SqlField]
        public bool ChronOrder { get; set; }
        [SqlField]
        public DateTime CreateDate { get; set; }
        [SqlField]
        public DateTime? LastUpdate { get; set; }

        static rrForum()
        {
            RecordMapper.Register(typeof(rrForum), typeof(SqlField));
        }
        public rrForum(SqlDataReader reader)
        {
            RecordMapper.ReadObject(this, reader);
        }
    }

    public class rrForumDB
    {
        public static rrForum GetForum(int ForumId)
        {
            rrForum result = null;
            using (SqlConnection conn = new SqlConnection(SQL.RifleRange))
            {
                try
                {
                    SqlCommand cmd = new SqlCommand("dbo.usp_GetForum", conn);
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("@ForumId", ForumId);
                    conn.Open();
                    SqlDataReader reader = cmd.ExecuteReader();
                    if (reader != null && !reader.IsClosed)
                    {
                        while (reader.Read()) result = new rrForum(reader);
                    }

                }
                catch (Exception ex)
                {
                    throw new Exception(ex.Message, ex);
                }
            }
            return result;
        }

    }
}
